#!/bin/bash

if [ $1 == 'user' ]; then
	echo -e "\n\033[1mPOST"
	curl -i -H "Content-Type: application/json" -X POST -d '{"username":"teste", "nome":"Teste da Silva"}' http://localhost:5000/api/user
	curl -i -H "Content-Type: application/json" -X POST -d '{"username":"teste2", "nome":"Teste Gouvea"}' http://localhost:5000/api/user
	curl -i -H "Content-Type: application/json" -X POST -d '{"username":"jonathan", "nome":"Jonathan Gouvea"}' http://localhost:5000/api/user

	echo -e "\n\033[1mGET"
	curl -i http://localhost:5000/api/user
	curl -i http://localhost:5000/api/user/teste

	echo -e "\n\033[1mDELETE"
	curl -i -X DELETE http://localhost:5000/api/user/teste2

	echo -e "\n\033[1mPUT"
	curl -i -H "Content-Type: application/json" -X PUT -d '{"nome":"O TESTE"}' http://localhost:5000/api/user/teste

	echo -e "\n"
	curl -i http://localhost:5000/api/user
fi

if [ $1 == 'topico' ]; then
	echo -e "\n\033[1mPOST"
	curl -i -H "Content-Type: application/json" -X POST -d '{"titulo":"REST", "autor":"Teste", "descricao":"Uma introdução à REST API"}' http://localhost:5000/api/topico
	curl -i -H "Content-Type: application/json" -X POST -d '{"titulo":"Java", "autor":"Jonathan", "descricao":"Bomba!"}' http://localhost:5000/api/topico
	curl -i -H "Content-Type: application/json" -X POST -d '{"titulo":"Python", "autor":"Teste", "descricao":"Um hino"}' http://localhost:5000/api/topico

	echo -e "\n\033[1mGET"
	curl -i http://localhost:5000/api/topico
	curl -i http://localhost:5000/api/topico/1
	curl -i http://localhost:5000/api/topico_autor/Jonathan

	echo -e "\n\033[1mDELETE"
	curl -i -X DELETE http://localhost:5000/api/topico/2

	echo -e "\n\033[1mPUT"
	curl -i -H "Content-Type: application/json" -X PUT -d '{"autor":"Jonathan"}' http://localhost:5000/api/topico/3

	echo -e "\n"
	curl -i http://localhost:5000/api/topico
fi
